apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cosa
  namespace: fedora-coreos
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: "quay.io/coreos-assembler/coreos-assembler:master"
      name: "master"
      referencePolicy:
        type: Local
