apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fedora
  namespace: fedora-coreos
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: "registry.fedoraproject.org/fedora:30"
      name: "30"
      referencePolicy:
        type: Local
