apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pipeline
  namespace: fedora-coreos
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: src:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/fedora-coreos-tekton
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: cosa:master
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ImageChange
    - type: ConfigChange
