apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-fcos
  namespace: fedora-coreos
spec:
  tasks:
    - name: init
      taskRef:
        name: script
      params:
        - name: SCRIPT
          value: "init"
    - name: build
      taskRef:
        name: script
      params:
        - name: SCRIPT
          value: "build"
