apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-client
  namespace: fedora-coreos
spec:
  inputs:
    params:
      - name: ARGS
        description: The OpenShift CLI arguments to run
        default: help
  steps:
    - name: oc
      image: quay.io/openshift-pipeline/openshift-cli:latest
      command: ["/usr/local/bin/oc"]
      args:
        - "${inputs.params.ARGS}"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: script
  namespace: fedora-coreos
spec:
  inputs:
    params:
      - name: SCRIPT
        description: Script to run in cosa image
      - name: ARGS
        description: Script params
        default: --help
  steps:
    - name: script
      image: image-registry.openshift-image-registry.svc:5000/fedora-coreos/src:latest
      command: ["/code/scripts/${inputs.params.SCRIPT}.py"]
      args:
        - "${inputs.params.ARGS}"
