apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: script
  namespace: fedora-coreos
spec:
  inputs:
    params:
      - name: SCRIPT
        description: Script to run in cosa image
      - name: ARGS
        description: Script params
        default: --help
  steps:
    - name: script
      image: src:latest
      command: ["/bin/python3"]
      args:
        - "/srv/scripts/${inputs.params.SCRIPT}.py"
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "1Gi"
      volumeMounts:
        - name: kvm
          mountPath: /dev/kvm
  volumes:
    - name: kvm
      hostPath:
        path: /dev/kvm
