apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: script
  namespace: fedora-coreos
spec:
  inputs:
    resources:
      - name: src
        type: git
    params:
      - name: SCRIPT
        description: Script to run in cosa image
      - name: ARGS
        description: Script params
        default: --help
  steps:
    - name: script
      image: quay.io/coreos-assembler/coreos-assembler:master
      command: ["/bin/bash"]
      args:
        - -c
        - "git clone --branch ${inputs.resources.src.revision} ${inputs.resources.src.url} /srv/scripts"
        - "/srv/scripts/${inputs.params.SCRIPT}.py"
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "1Gi"
      volumeMounts:
        - name: kvm
          mountPath: /dev/kvm
  volumes:
    - name: kvm
      hostPath:
        path: /dev/kvm
