apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: scripts
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:vrutkovs/fedora-coreos-tekton.git
