resources:
  - 01-namespace.yaml
  - 02-imagestream-cosa.yaml
  - 03-imagestream-pipeline.yaml
  - 04-buildconfig.yaml
  - 05-olm-subscription.yaml
  - 06-tekton-task.yaml
  - 07-pipeline.yaml
  - 08-tekton-rolebinding.yaml
